# Alice in Puzzleland



> “Mad Hatter: “Why is a raven like a writing-desk?”

>“Have you guessed the riddle yet?” the Hatter said, turning to Alice again.

>“No, I give it up,” Alice replied: “What’s the answer?”

>“I haven’t the slightest idea,” said the Hatter” 

>>― Lewis Carroll, Alice in Wonderland

### We are headed on a journey through a brain-wracking twist on Wonderland. Alice has tumbled down the Rabbit Hole and into the world of logic, math, and programming. Each turn brings a new, mad, puzzle. Alice is a very clever girl, however, and this is her story in Puzzleland. Help Alice solve her way through nonsense, where everything is "curiouser and curiouser!"

<img src="https://62e528761d0685343e1c-f3d1b99a743ffa4142d9d7f1978d9686.ssl.cf2.rackcdn.com/files/87342/width926/image-20150703-20493-1aeooun.jpg" width = 500px>





## Down the Rabbit Hole
Alice is falling down the rabbit hole, wondering which country she might be in.

## The Pool of Tears

Alice has discovered a room: There is a very small door, a very tall table, and very small key sitting upon that very tall table.

## Advice from a Caterpillar

This caterpillar speaks in anagrams, palendromes, and other stringy messes.

### Pig and Pepper
Is it a baby? Is it a pig? Let's do some feature recognition. Don't forget the ***noise*** from all the sneezing.

## The Mad Tea Party

A Constraint Satisfaction Problem uses search to determine a solution that does not violate given constraints. A common example is the "Map Color Problem". You are tyring to color a map of the United States, and you have 4 available colors (no mixing!) : Red Green Yellow Blue. The constraint is that no adjacent states may be the same color. 

But we are in Puzzleland! We don't deal with serious problems, only silly ones! It just so happens that Alice comes upon a tea party, where she joins the Mad Hatter, the Dormouse, and the March Hare stuck at tea time.

> *'Yes, that's it,' said the Hatter with a sigh: 'it's always tea-time, and we've no time to wash the things between whiles.'*

>*'Then you keep moving round, I suppose?' said Alice.*

>*'Exactly so,' said the Hatter: 'as the things get used up.'*

>*'But what happens when you come to the beginning again?' Alice ventured to ask.*

>*'Suppose we change the subject,' the March Hare interrupted.*

Let us define a Constraint Satisfaction Problem for how everyone can move around the tea table when it's time to change places!

> **Variables: **

>>Possible seats to be filled around the table. Let's say there is 8.

> **Domain: **

>>Each of the guests who can fill a seat around the table. Alice, the Mad Hatter, the March Hare, and the Dormouse.

> **Constraints:** 

>>You cannot sit in a seat that someone else was just sitting in (including yourself).

We are ready to start coding!


<!--<center><div><img src = "changeplace.gif" alt = "" width=400px  style="display:inline;"> </div></center>-->




In [1]:
import numpy as np


#number of places at the tea table
n = 12
guests = ["Alice","MadHatter","MarchHare","Dormouse"]
#initialize our places so no one is sitting there

domain = dict.fromkeys(set(range(n)))

#randomly assign seating
initialize= np.random.choice(n, len(guests),replace=False)
count=0
for i in initialize:
    domain[i]=guests[count]
    count+=1
for i in domain:
        print(i,domain[i])

        
def apply_constraint(domain,guests):
    #search for the right seats
    #define list of possible seats (anywhere not currently occupied by anyone)
    possible = []
    for k in domain:
        if domain[k]== None:
            possible.append(k)
    if not len(possible)>=len(guests): 
        print("This simply isn't possible! Though... I've often believed six impossible things before breakfast.")
    
    else:
        #now you can assign the guests to any of these seats and it will be a solution
        assigns = [np.random.choice(possible,len(guests),replace=False),np.random.choice(guests,len(guests),replace=False)]
        domain = dict.fromkeys(set(range(len(domain))))

        for val in zip(assigns[0],assigns[1]):
            domain[val[0]]=val[1]
        print("\n")   
        for i in domain:
            print(i,domain[i])

def print_table(domain):
    dim = np.ceil(len(domain)/4)
    print(dim)
    
    

apply_constraint(domain,guests)

#we define a constraint where we return a boolean where we check
#if anyone is sitting in a seat that has been sat in before

#def check_constraint(domain):
    #return True if constraint met
    


0 Alice
1 None
2 Dormouse
3 None
4 MadHatter
5 None
6 None
7 MarchHare
8 None
9 None
10 None
11 None


0 None
1 Alice
2 None
3 None
4 None
5 Dormouse
6 None
7 None
8 MarchHare
9 None
10 None
11 MadHatter


3
[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
Point(350.0, 300.0)


In [10]:
from graphics import *

def main():
    
    #make a matrix with the number of guests to move around
    n=12
    screen_width=700
    screen_height=600
    midw=screen_width/2
    midh=screen_height/2
    dim = int(np.ceil(n/4))
    print(dim)
    table = np.zeros(shape=[4,dim,2])
    #0: top of table, 1:left 2: right 3: bottom 
    print(table)
    table_width = 100*dim
    table_height = 100 * dim
    
        
    
    
    
    
    win = GraphWin('Tea Time', screen_width, screen_height)
    win.setCoords(0, screen_height, screen_width, 0)
    win.setBackground('pink')
    message = Text(Point(win.getWidth()/2, 30), 'Where is everyone sitting?')
    message.setTextColor('black')
    message.setStyle('italic')
    message.setSize(20)
    message.draw(win)
    #myImage = Image(Point(win.getWidth()/2,win.getHeight()/2), 'teatable.gif')
    #myImage.draw(win)
    
    #position the table in the center:
    
    center = Point(midw,midh)
    print(center)
    t = Rectangle(Point((midw-table_width/2),(midh-table_height/2)),Point((midw+table_width/2),(midh+table_height/2)))
    t.setFill("white")
    #t.draw(win)
    
    x=40
    y=40
    
    #top and bottom
    for val in range(0,len(table[0])):
        table[0][val]=[(midw-table_width/2)+x,(midh-table_height/2)-10]
        table[3][val]=[(midw-table_width/2)-10,(midh-table_height/2)+y]
        table[1][val]=[(midw+table_width/2)+10,(midh-table_height/2)+y]
        table[2][val]=[(midw-table_width/2)+x,(midh+table_height/2)+10]
        
        x+=100
        y+=100
    print(table[3])
   
   
        
        
  
    
    i=0

  
    
                
                
    
    
    rect = Rectangle(Point(150,150), Point(450,350))
    rect.draw(win)
    rect.setFill("white")
    alice = Image(Point(200,100), 'alice.gif')
    alice.draw(win)
    hatter = Image(Point(400,100), 'madhatter.gif')
    hatter.draw(win)
    hare = Image(Point(200,400), 'march.gif')
    hare.draw(win)
    mouse = Image(Point(400,400), 'dormouse.gif')
    mouse.draw(win)
    
    win.getMouse()
    win.close()
    
  

main()


3
[[[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]

 [[ 0.  0.]
  [ 0.  0.]
  [ 0.  0.]]]
Point(350.0, 300.0)
[[ 190.  190.]
 [ 190.  290.]
 [ 190.  390.]]


## We're All Mad Here

Let's play with decision trees to decide whether or not Alice is likely to go mad. 


In [29]:
import collections
import math

def entropy(class_probabilities):
    return sum(-p * math.log(p,2) for p in class_probabilities if p)

def class_probabilities(labels):
    total_count = len(labels)
    return [count / total_count for count in collections.Counter(labels).values()]

def data_entropy(labeled_data):
    labels = [label for _, label in labeled_data]
    probabilities = class_probabilities(labels)
    return entropy(probabilities)

def partition_entropy(subsets):
    total_count = sum(len(subset) for subset in subsets)
    
    return sum( data_entropy(subset) * len(subset) / total_count for subset in subsets)

'''inputs = [
    
    ({'level':'Senior', 'lang':'Java', 'tweets':'no', 'phd':'no'}, False), #1
    ({'level':'Senior', 'lang':'Java', 'tweets':'no', 'phd':'yes'}, False),
    ({'level':'Mid', 'lang':'Python', 'tweets':'no', 'phd':'no'}, True),
    ({'level':'Junior', 'lang':'Python', 'tweets':'no', 'phd':'no'}, True),
    ({'level':'Junior', 'lang':'R', 'tweets':'yes', 'phd':'no'}, True), #5
    ({'level':'Junior', 'lang':'R', 'tweets':'yes', 'phd':'yes'}, False),
    ({'level':'Mid', 'lang':'R', 'tweets':'yes', 'phd':'yes'}, True),
    ({'level':'Senior', 'lang':'Python', 'tweets':'no', 'phd':'no'}, False),
    ({'level':'Senior', 'lang':'R', 'tweets':'yes', 'phd':'no'}, True),
    ({'level':'Junior', 'lang':'Python', 'tweets':'yes', 'phd':'no'}, True), #10
    ({'level':'Senior', 'lang':'Python', 'tweets':'yes', 'phd':'yes'}, True),
    ({'level':'Mid', 'lang':'Python', 'tweets':'no', 'phd':'yes'}, True),
    ({'level':'Mid', 'lang':'Java', 'tweets':'yes', 'phd':'no'}, True),
    ({'level':'Junior', 'lang':'Python', 'tweets':'no', 'phd':'yes'}, False) #14
    ]'''
inputs = [
    
    ({'cat_listen':'no', 'plays_croquet':'no', 'drinks_tea':'yes', 'size':'normal', 'how_late':'not'}, False), 
    ({'cat_listen':'yes', 'plays_croquet':'yes', 'drinks_tea':'yes', 'size':'big','how_late':'very'}, True),
    ({'cat_listen':'yes', 'plays_croquet':'no', 'drinks_tea':'yes', 'size':'small','how_late':'somewhat'}, True),
    ({'cat_listen':'no', 'plays_croquet':'yes', 'drinks_tea':'yes', 'size':'normal','how_late':'very'}, False),
    ({'cat_listen':'no', 'plays_croquet':'yes', 'drinks_tea':'yes', 'size':'normal','how_late':'not'}, False),
    ({'cat_listen':'no', 'plays_croquet':'no', 'drinks_tea':'no', 'size':'normal','how_late':'somewhat'}, True),
    ({'cat_listen':'no', 'plays_croquet':'no', 'drinks_tea':'yes', 'size':'normal','how_late':'very'}, False),
    ({'cat_listen':'yes', 'plays_croquet':'no', 'drinks_tea':'yes', 'size':'normal','how_late':'not'}, False),
    ({'cat_listen':'yes', 'plays_croquet':'no', 'drinks_tea':'no', 'size':'small','how_late':'very'}, True),
    ({'cat_listen':'no', 'plays_croquet':'no', 'drinks_tea':'yes', 'size':'normal','how_late':'not'}, False),
    ({'cat_listen':'yes', 'plays_croquet':'yes', 'drinks_tea':'yes', 'size':'big','how_late':'somewhat'}, True),
    ({'cat_listen':'no', 'plays_croquet':'no', 'drinks_tea':'no', 'size':'normal','how_late':'very'}, True)
    
    
]
def partition_by(inputs,attribute):
    groups = collections.defaultdict(list)
    for input in inputs:
        key = input[0][attribute]
        groups[key].append(input)
    return groups

def partition_entropy_by(inputs, attribute):
    partitions = partition_by(inputs,attribute)
    return partition_entropy(partitions.values())

for key in ['cat_listen','plays_croquet','drinks_tea','size','how_late']:
    print (key, partition_entropy_by(inputs,key))
    print("\n")


    #tweets is 0.0 so we know we definitively split
    
#split by the lowest entropy: how late you are
    
very_inputs = [(input, label) for input, label in inputs if input["how_late"]=="somewhat"]

for key in ['cat_listen','plays_croquet','drinks_tea','size']:
    print (key, partition_entropy_by(very_inputs, key))


cat_listen 0.8042903712002691


plays_croquet 1.0


drinks_tea 0.6887218755408672


size 0.5408520829727552


how_late 0.4045627476894453


cat_listen 0.0
plays_croquet 0.0
drinks_tea 0.0
size 0.0


## Who Stole the Tarts?

Bayesian inference given Alice's evidence and the other evidence surrounding the charges